-- 280_property_manuals.sql
-- Runs on BOTH databases.
--
-- New table backing B3: per-property operational manuals, replacing two
-- pieces of data that were hardcoded and duplicated across the two client
-- files with no way to edit them in-app:
--   - INVENTORY (demo/domestic.html) — the cleaner's per-property
--     room/item checklist during a clean.
--   - INSP_CHECKLIST (demo/index_fixed.html) — was a single GLOBAL list
--     used for every property's inspection form; now per-property too.
-- A third section, 'faq', is new — guest-facing Q&A entries insertable
-- into Guest Timeline (B1) messages. Starts empty per property; no real
-- FAQ content existed anywhere to seed it from, so seeding fake answers
-- would just be new placeholder content, which is exactly what this
-- migration is trying to get rid of elsewhere.
--
-- One row per (property, section); content shape depends on section:
--   inventory:  {"rooms":[{"room","icon","items":[...]}]}
--   inspection: {"checklist":[{"key","label"}]}
--   faq:        {"entries":[{"q","a"}]}

CREATE TABLE IF NOT EXISTS public.property_manuals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  property_id uuid NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  section text NOT NULL CHECK (section IN ('inventory','inspection','faq')),
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (property_id, section)
);

CREATE OR REPLACE FUNCTION public.property_manuals_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS property_manuals_updated_at ON public.property_manuals;
CREATE TRIGGER property_manuals_updated_at
BEFORE UPDATE ON public.property_manuals
FOR EACH ROW EXECUTE FUNCTION public.property_manuals_updated_at();

ALTER TABLE public.property_manuals ENABLE ROW LEVEL SECURITY;

-- Same shape as domestics/tasks: any authenticated org member can read and
-- write — this is day-to-day operational content (Nina updates it as much
-- as Nicole/Silja), not something to admin-gate.
DROP POLICY IF EXISTS property_manuals_select ON public.property_manuals;
CREATE POLICY property_manuals_select ON public.property_manuals FOR SELECT USING (
  auth.role() = 'authenticated' AND org_id = current_org_id()
);

DROP POLICY IF EXISTS property_manuals_insert ON public.property_manuals;
CREATE POLICY property_manuals_insert ON public.property_manuals FOR INSERT WITH CHECK (
  auth.role() = 'authenticated' AND org_id = current_org_id()
);

DROP POLICY IF EXISTS property_manuals_update ON public.property_manuals;
CREATE POLICY property_manuals_update ON public.property_manuals FOR UPDATE USING (
  auth.role() = 'authenticated' AND org_id = current_org_id()
) WITH CHECK (
  auth.role() = 'authenticated' AND org_id = current_org_id()
);

-- ── Seed: real data transcribed as-is from the hardcoded structures it
-- replaces (INVENTORY in demo/domestic.html, INSP_CHECKLIST in
-- demo/index_fixed.html) — nothing invented, generated by a script that
-- read those exact objects so there's no manual-transcription risk.
-- Inspection checklist seeded identically for both properties since it
-- was previously one shared global list; now editable per property going
-- forward if they ever need to diverge.

INSERT INTO public.property_manuals (org_id, property_id, section, content) VALUES
  ('5966bc67-5c2f-45ae-8519-9b7eaeee09f4', 'e9737638-d83a-4947-940a-8746789e4d9f', 'inventory', '{"rooms":[{"room":"Kitchen","icon":"🍳","items":["Plates (×4)","Bowls (×4)","Mugs (×4)","Glasses (×4)","Cutlery set (×4)","Pots & pans","Kettle","Toaster","Microwave","Chopping board","Dish cloths (×2)","Washing liquid present","Washing machine tablet (×1)","Coffee plunger present","Mixer/blender present"]},{"room":"Bathroom","icon":"🚿","items":["Bath towels (×2)","Hand towels (×2)","Wiper/squeegee present","Hair dryer present"]},{"room":"Bedroom 1","icon":"🛏","items":["Pillows (×2)","Pillow cases (×2)","Duvet & cover","Mattress protector","Hangers (≥6)","Bedside lamp working"]},{"room":"Bedroom 2","icon":"🛏","items":["Pillows (×2)","Pillow cases (×2)","Duvet & cover","Mattress protector","Hangers (≥6)","Bedside lamp working"]},{"room":"Living Room","icon":"🛋","items":["TV remote present","Fan remote present","Cushions (all present)","Throw blanket","All lights working"]},{"room":"General","icon":"🔑","items":["Remote for entry present","Welcome book present","No visible damage to walls/furniture","Windows & doors lock properly","Rubbish removed"]}]}'::jsonb)
  ON CONFLICT (property_id, section) DO NOTHING;

INSERT INTO public.property_manuals (org_id, property_id, section, content) VALUES
  ('5966bc67-5c2f-45ae-8519-9b7eaeee09f4', '83b2a84a-5451-4be5-a84f-2efc0d2602d5', 'inventory', '{"rooms":[{"room":"Kitchen","icon":"🍳","items":["Plates (×6)","Bowls (×6)","Mugs (×6)","Glasses (×6)","Wine glasses (×4)","Cutlery set (×6)","Pots & pans","Kettle","Toaster","Microwave","Chopping boards (×2)","Dish cloths (×2)","Washing liquid present","Washing machine tablet (×1)"]},{"room":"Main Bathroom","icon":"🚿","items":["Bath towels (×2)","Hand towels (×2)","Hair dryer present","Shower/bath clean"]},{"room":"Guest WC","icon":"🚽","items":["Hand towel (×1)","Toilet clean"]},{"room":"Main Bedroom","icon":"🛏","items":["Pillows (×2)","Pillow cases (×2)","Duvet & cover","Mattress protector","Hangers (≥8)","Bedside lamps (×2) working"]},{"room":"Bedroom 2","icon":"🛏","items":["Pillows (×2)","Pillow cases (×2)","Duvet & cover","Mattress protector","Hangers (≥6)","Light working"]},{"room":"Bedroom 3","icon":"🛏","items":["Pillows (×2)","Pillow cases (×2)","Duvet & cover","Mattress protector","Hangers (≥6)","Light working"]},{"room":"Living Room","icon":"🛋","items":["TV remote present","Cushions (all present)","All lights working"]},{"room":"General","icon":"🔑","items":["Remote for entry present","No visible damage to walls/furniture","Windows & doors lock properly","Pool gate locked","Garden furniture in order","Rubbish removed","Gas bottle — check if empty"]}]}'::jsonb)
  ON CONFLICT (property_id, section) DO NOTHING;

INSERT INTO public.property_manuals (org_id, property_id, section, content) VALUES
  ('5966bc67-5c2f-45ae-8519-9b7eaeee09f4', 'e9737638-d83a-4947-940a-8746789e4d9f', 'inspection', '{"checklist":[{"key":"entrance","label":"Entrance & front door"},{"key":"living","label":"Living room"},{"key":"kitchen","label":"Kitchen & appliances"},{"key":"bathroom","label":"Bathroom(s)"},{"key":"bedrooms","label":"Bedroom(s)"},{"key":"balcony","label":"Balcony / outdoor area"},{"key":"geyser","label":"Geyser & hot water"},{"key":"electrical","label":"Lights & plugs"},{"key":"wifi","label":"WiFi & TV working"},{"key":"inventory","label":"Inventory complete"},{"key":"maintenance","label":"No maintenance issues"},{"key":"cleanliness","label":"General cleanliness"}]}'::jsonb)
  ON CONFLICT (property_id, section) DO NOTHING;

INSERT INTO public.property_manuals (org_id, property_id, section, content) VALUES
  ('5966bc67-5c2f-45ae-8519-9b7eaeee09f4', '83b2a84a-5451-4be5-a84f-2efc0d2602d5', 'inspection', '{"checklist":[{"key":"entrance","label":"Entrance & front door"},{"key":"living","label":"Living room"},{"key":"kitchen","label":"Kitchen & appliances"},{"key":"bathroom","label":"Bathroom(s)"},{"key":"bedrooms","label":"Bedroom(s)"},{"key":"balcony","label":"Balcony / outdoor area"},{"key":"geyser","label":"Geyser & hot water"},{"key":"electrical","label":"Lights & plugs"},{"key":"wifi","label":"WiFi & TV working"},{"key":"inventory","label":"Inventory complete"},{"key":"maintenance","label":"No maintenance issues"},{"key":"cleanliness","label":"General cleanliness"}]}'::jsonb)
  ON CONFLICT (property_id, section) DO NOTHING;

-- End 280_property_manuals.
