-- 908_guesthouse_rooms.sql
-- Runs on BOTH databases.
--
-- Owner: "Before starting to test, I would like to have some owners of
-- guesthouses to be able to use it as well. Rooms are being booked etc,
-- it's just rooms designated. They might have daily cleaners and plan
-- accordingly."
--
-- This was on the roadmap as p2-7, filed "nice to have". It is not: if the
-- first testers run guesthouses, it decides whether they can use the
-- product at all.
--
-- ══ WHY A ROOM IS NOT A NEW KIND OF THING ═════════════════════════
--
-- The tempting design is a rooms table. It is the wrong one. Everything
-- that makes a room hard is already solved for a property: a room has its
-- own calendar, its own iCal feed from Booking.com, its own nightly rate,
-- its own cleaning, its own occupancy. A room IS a property that happens
-- to sit inside another one.
--
-- So rooms are properties with a parent, and every table that already
-- points at a property — bookings, domestics, ical_feeds, property_manuals,
-- inspections, property_users — keeps working untouched, per room, on day
-- one. A rooms table would have meant teaching all of them a second way to
-- identify a place, which is how you end up with two half-working
-- calendars.
--
-- ONE LEVEL ONLY. A room cannot contain rooms. Enforced below rather than
-- documented, because "obviously nobody would" is how a tree ends up with
-- a cycle in it and every roll-up query hangs.
--
-- ── "WHAT IF EACH ROOM HAS ITS OWN iCAL?" ─────────────────────────
--
-- Then it already works, and this is the reason the design is right
-- rather than merely convenient.
--
-- ical_feeds.property_id points at a property, and a room is a property,
-- so every room gets its own set of feeds — Airbnb, Booking.com,
-- LekkeSlaap — with no schema change and no importer change. That is
-- exactly how the platforms publish them: Booking.com gives you one iCal
-- per room type, not one per building, so a guesthouse's feeds map one to
-- one onto rooms and there is nothing to reconcile.
--
-- It works outbound too. properties.ical_token (897) is per property, so
-- each room also EXPORTS its own calendar, and a guesthouse owner can hand
-- Booking.com a per-room feed generated by HEP.
--
-- Had rooms been a separate table, every one of those paths would have
-- needed a second way to identify a place: the importer, the token, the
-- feed table, the calendar endpoint. This is the difference between a
-- morning's work and a fortnight's.
--
-- ══ BILLING: A GUESTHOUSE IS ONE PROPERTY ═════════════════════════
--
-- The owner's decision, asked directly. An eight-room guesthouse counts as
-- one toward the plan limit, so Starter at R350 is genuinely usable by a
-- small guesthouse — which matters most right now, when the job is
-- recruiting them as testers rather than extracting R750 from them.
--
-- Worth knowing, and not obvious: properties_limit has existed as a column
-- since 830 and NOTHING HAS EVER ENFORCED IT. The pricing page promises
-- "up to 3 / up to 10 / unlimited" and any customer can add fifty. That is
-- a slow leak with apartments and an instant one with guesthouses, so the
-- counting function is defined here — correctly, counting guesthouses
-- rather than rooms — ready for whenever the limit is actually applied.

-- ══ 0. DRIFT FOUND WHILE APPLYING THIS ════════════════════════════
--
-- bookings.is_owner_block exists in production and did not exist in
-- staging, so property_occupancy() below compiled against one database and
-- failed on the other. Closed by adding the column to staging with
-- production's definition rather than by writing the function
-- defensively — a query that silently means something different on
-- staging is worse than one that will not compile, because the first kind
-- gets promoted.
ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS is_owner_block boolean NOT NULL DEFAULT false;

-- ══ 1. ROOMS ══════════════════════════════════════════════════════
ALTER TABLE public.properties
  ADD COLUMN IF NOT EXISTS parent_id uuid REFERENCES public.properties(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS properties_parent_idx ON public.properties (parent_id);

COMMENT ON COLUMN public.properties.parent_id IS
  'The guesthouse this room belongs to. NULL for a whole property (flat, house, or the guesthouse itself). One level only — a room cannot contain rooms.';

-- properties.type is not free text — 001 put a CHECK on it allowing
-- apartment/house/studio/villa/cabin/other, which is easy to miss because
-- only two of those are ever used. So the two new kinds have to be added
-- to the constraint, not merely written into a row: 'guesthouse' is a
-- parent that has rooms, 'room' is one of them.
ALTER TABLE public.properties DROP CONSTRAINT IF EXISTS properties_type_check;
ALTER TABLE public.properties ADD CONSTRAINT properties_type_check
  CHECK (type = ANY (ARRAY['apartment','house','studio','villa','cabin','guesthouse','room','other']));

-- ── The guard ─────────────────────────────────────────────────────
--
-- Four ways to make a nonsense tree, all of them cheap to prevent and
-- expensive to discover later. The tenancy one is the important one: an
-- unchecked parent_id lets a row be attached to ANOTHER AGENCY'S property,
-- which is precisely the class of bug the whole org_id scheme exists to
-- stop. RLS does not catch it, because the row being written is your own.
CREATE OR REPLACE FUNCTION public.properties_parent_guard()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
  IF NEW.parent_id IS NULL THEN RETURN NEW; END IF;

  IF NEW.parent_id = NEW.id THEN
    RAISE EXCEPTION 'A property cannot be its own guesthouse.' USING ERRCODE = '22023';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.properties p
                  WHERE p.id = NEW.parent_id AND p.org_id = NEW.org_id) THEN
    RAISE EXCEPTION 'A room must belong to a guesthouse in the same organisation.'
      USING ERRCODE = '42501';
  END IF;

  IF EXISTS (SELECT 1 FROM public.properties p
              WHERE p.id = NEW.parent_id AND p.parent_id IS NOT NULL) THEN
    RAISE EXCEPTION 'A room cannot belong to another room.' USING ERRCODE = '22023';
  END IF;

  IF EXISTS (SELECT 1 FROM public.properties p WHERE p.parent_id = NEW.id) THEN
    RAISE EXCEPTION 'This property already has rooms, so it cannot become a room itself.'
      USING ERRCODE = '22023';
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS properties_parent_guard ON public.properties;
CREATE TRIGGER properties_parent_guard
  BEFORE INSERT OR UPDATE OF parent_id, org_id ON public.properties
  FOR EACH ROW EXECUTE FUNCTION public.properties_parent_guard();

-- ── DELETING A GUESTHOUSE ─────────────────────────────────────────
--
-- parent_id cascades, so removing a guesthouse removes its rooms. That
-- immediately ran into something that was already true and rarely noticed:
-- SIX tables reference properties with NO ACTION, so deleting any property
-- that has ever been used fails with a raw foreign-key error.
--
-- With flats that is a rare annoyance. With a guesthouse it is certain —
-- every room has an iCal feed, so the cascade hits one on the first room
-- and the whole delete aborts.
--
-- Only ical_feeds is changed here, because a feed for a property that no
-- longer exists is meaningless and there is nothing to preserve. The other
-- five are deliberately left blocking:
--
--   financial_transactions, domestic_services, booking_checklists, tasks,
--   property_users
--
-- Those carry history — money above all — and a DELETE that silently takes
-- financial records with it is not a convenience, it is a way to lose the
-- only record that a payment happened. Refusing is the correct behaviour;
-- what is missing is a readable message instead of a Postgres error, and
-- that is a UI job rather than a schema one.
ALTER TABLE public.ical_feeds DROP CONSTRAINT IF EXISTS ical_feeds_property_id_fkey;
ALTER TABLE public.ical_feeds ADD CONSTRAINT ical_feeds_property_id_fkey
  FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE;

-- ══ 2. WHAT THE CUSTOMER IS BILLED FOR ════════════════════════════
CREATE OR REPLACE FUNCTION public.org_billable_properties(p_org uuid)
RETURNS int LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT count(*)::int FROM public.properties
   WHERE org_id = p_org AND parent_id IS NULL;
$$;

COMMENT ON FUNCTION public.org_billable_properties(uuid) IS
  'Properties counted against the plan limit. A guesthouse is one, however many rooms it has — the owner''s decision, so that Starter is usable by a small guesthouse.';

REVOKE ALL ON FUNCTION public.org_billable_properties(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.org_billable_properties(uuid) TO authenticated;

-- ══ 3. DAILY SERVICING ════════════════════════════════════════════
--
-- Cleaning in HEP has always been CHECKOUT-DRIVEN: a departure raises a
-- turnover. A guesthouse services an occupied room while the guest is
-- still in it, which is a different trigger entirely, and no amount of
-- turnover logic produces it.
ALTER TABLE public.properties
  ADD COLUMN IF NOT EXISTS daily_service boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.properties.daily_service IS
  'Rooms serviced every day the guest is in residence, not only on departure. Off by default: a self-catering flat is cleaned between guests and nobody wants a cleaner knocking on day two.';

-- Materialised rather than derived, because a cleaner has to be able to
-- tick one off and a coordinator has to be able to assign it — both of
-- which need a row. Idempotent, so it is safe to run again over a range
-- that has already been generated; that matters because it will be, by
-- anyone who clicks the button twice.
CREATE OR REPLACE FUNCTION public.generate_daily_service(
  p_org uuid, p_from date, p_to date, p_cleaner text DEFAULT ''
)
RETURNS int LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE n int;
BEGIN
  -- Same shape as enforce_subscription_write() in 880: a signed-in user is
  -- pinned to their own org, and a server-side caller with no session is
  -- not gated at all. Without the second half this could never be run by a
  -- nightly job — which is where generating next week's servicing
  -- eventually belongs — and cannot be exercised from the SQL editor,
  -- which is how it was found.
  IF auth.uid() IS NOT NULL
     AND COALESCE(current_setting('request.jwt.claims', true)::jsonb ->> 'role', '') <> 'service_role'
     AND p_org IS DISTINCT FROM public.current_org_id() THEN
    RAISE EXCEPTION 'Not permitted.' USING ERRCODE = '42501';
  END IF;
  IF p_to < p_from THEN
    RAISE EXCEPTION 'End date is before the start date.' USING ERRCODE = '22023';
  END IF;
  -- A whole year in one click is somebody's typo, and it would write
  -- thousands of rows somebody then has to delete by hand.
  IF p_to - p_from > 92 THEN
    RAISE EXCEPTION 'Generate at most a quarter at a time.' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.domestics (org_id, property_id, date, type, status, cleaner)
  SELECT p_org, pr.short_key, d::date, 'daily_service', 'scheduled', COALESCE(p_cleaner, '')
    FROM public.properties pr
    JOIN public.bookings b
      ON b.property_id = pr.id
     AND b.is_active
     AND COALESCE(b.status, '') <> 'cancelled'
     -- An owner block is not a guest, and nobody services an empty room.
     AND COALESCE(b.is_owner_block, false) = false
    CROSS JOIN LATERAL generate_series(
      -- Not the arrival day: the room was prepared before they got there.
      -- Not the departure day: that is a turnover, which the existing
      -- checkout flow already raises. Servicing is the days in between.
      GREATEST(b.check_in_date::date + 1, p_from),
      LEAST(b.check_out_date::date - 1, p_to),
      interval '1 day') d
   WHERE pr.org_id = p_org
     AND pr.daily_service
     AND pr.short_key IS NOT NULL
     -- Never a second clean on a day that already has one, of any kind.
     -- A turnover and a service on the same date would send two people to
     -- the same room.
     AND NOT EXISTS (
       SELECT 1 FROM public.domestics x
        WHERE x.org_id = p_org
          AND x.property_id = pr.short_key
          AND x.date = d::date
          AND COALESCE(x.status, '') <> 'cancelled'
     );

  GET DIAGNOSTICS n = ROW_COUNT;
  RETURN n;
END $$;

COMMENT ON FUNCTION public.generate_daily_service(uuid, date, date, text) IS
  'Creates a daily_service clean for every night a guest is in residence, excluding arrival and departure days. Idempotent — skips any date that already has a clean, so running it twice is harmless.';

REVOKE ALL ON FUNCTION public.generate_daily_service(uuid, date, date, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_daily_service(uuid, date, date, text) TO authenticated;

-- ══ 4. OCCUPANCY THAT MEANS SOMETHING FOR A GUESTHOUSE ════════════
--
-- A guesthouse's occupancy is room-nights sold over room-nights available.
-- Averaging the occupancy of each room gives a different and wrong number
-- as soon as the rooms have different availability.
CREATE OR REPLACE FUNCTION public.property_occupancy(
  p_property uuid, p_from date, p_to date
)
RETURNS TABLE (nights_sold int, nights_available int, pct numeric)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH scope AS (
    -- WHAT CAN ACTUALLY BE SOLD. If this property has rooms then the rooms
    -- are the sellable units and the guesthouse itself is a building, not a
    -- bed; counting it as well inflates available room-nights and quietly
    -- understates occupancy — a two-room guesthouse read 33% where the true
    -- figure was 50%, which is the difference between a business that looks
    -- like it is failing and one that is half full.
    -- With no rooms, the property is the unit, and this reduces to the
    -- ordinary flat-or-house case.
    SELECT p.id FROM public.properties p
     WHERE p.org_id = public.current_org_id()
       AND (
         p.parent_id = p_property
         OR (p.id = p_property
             AND NOT EXISTS (SELECT 1 FROM public.properties c WHERE c.parent_id = p_property))
       )
  ),
  sold AS (
    SELECT count(*)::int AS n
      FROM public.bookings b
      JOIN scope s ON s.id = b.property_id
      CROSS JOIN LATERAL generate_series(
        GREATEST(b.check_in_date::date, p_from),
        LEAST(b.check_out_date::date - 1, p_to),
        interval '1 day') d
     WHERE b.is_active
       AND COALESCE(b.status,'') <> 'cancelled'
       AND COALESCE(b.is_owner_block,false) = false
  )
  SELECT sold.n,
         ((SELECT count(*) FROM scope) * (p_to - p_from + 1))::int,
         CASE WHEN (SELECT count(*) FROM scope) = 0 OR p_to < p_from THEN 0
              ELSE round(100.0 * sold.n /
                   ((SELECT count(*) FROM scope) * (p_to - p_from + 1)), 1) END
    FROM sold;
$$;

COMMENT ON FUNCTION public.property_occupancy(uuid, date, date) IS
  'Room-nights sold over room-nights available. Called on a guesthouse it covers every room; called on a flat it covers just that flat. Not an average of per-room percentages, which is a different and wrong number once rooms differ in availability.';

REVOKE ALL ON FUNCTION public.property_occupancy(uuid, date, date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.property_occupancy(uuid, date, date) TO authenticated;

-- Nothing is backfilled. Every existing property keeps parent_id NULL and
-- daily_service false, which is exactly what a flat or a house is, so no
-- existing agency sees any change at all.

-- End 908_guesthouse_rooms.
